#!/usr/bin/env node
/**
 * Design preview for the renderer shell — no Electron, no main process.
 *
 * Serves `ui/` over HTTP and injects a stub `window.electronAPI` (built from
 * the real bundled catalogue) before the shell scripts run, so the whole
 * interface can be inspected and reviewed in a normal browser:
 *
 *     npm run preview:shell            # http://127.0.0.1:4317
 *     npm run preview:shell -- --port 5000
 *
 * `?light` renders the light theme, `?reset` clears the remembered UI state.
 *
 * This is a *preview*: it stubs IPC, never opens a WebContentsView and never
 * touches config or sessions on disk. Nothing here is loaded by the packaged
 * app.
 */

const http = require('http');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const UI_DIR = path.join(ROOT, 'ui');
const args = process.argv.slice(2);
const flag = (name, fallback) => {
  const i = args.indexOf(`--${name}`);
  return i !== -1 && args[i + 1] ? args[i + 1] : fallback;
};
const PORT = Number(flag('port', process.env.PREVIEW_PORT || 4317));
const HOST = flag('host', '0.0.0.0');

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.svg': 'image/svg+xml'
};

function readJson(relative, fallback) {
  try {
    return JSON.parse(fs.readFileSync(path.join(ROOT, relative), 'utf8'));
  } catch (error) {
    console.warn(`[preview] ${relative} unavailable (${error.message})`);
    return fallback;
  }
}

const catalogue = readJson('data/catalog.json', { services: [] });
const pkg = readJson('package.json', { version: '0.0.0' });

const services = Array.isArray(catalogue.services) ? catalogue.services : [];
const enabled = services.slice(0, 6).map((s) => s.id);

// A believable set of login states: one signed in, one signed out, one
// mid-challenge, the rest unchecked. Enough to exercise every chip and dot.
const loginStates = {};
enabled.forEach((id, index) => {
  if (index === 0) loginStates[id] = { state: 'logged-in', expiresAt: Date.now() + 864e5, lastCheckedAt: Date.now() - 6e5, hasSnapshot: true };
  else if (index === 1) loginStates[id] = { state: 'logged-out', reason: 'cookie expired', lastCheckedAt: Date.now() - 12e5 };
  else if (index === 2) loginStates[id] = { state: 'challenge', reason: 'cloudflare', lastCheckedAt: Date.now() - 4e5 };
  else loginStates[id] = { state: 'unknown' };
});

const config = {
  enabledServices: enabled,
  blockingEnabled: true,
  strictBlocking: false,
  maxActiveServices: 3,
  hibernateTabs: true,
  hibernateAfterMinutes: 15,
  darkMode: true,
  minimizeToTray: true,
  launchAtLogin: false,
  useProxy: false,
  proxyUrl: '',
  globalShortcut: 'CommandOrControl+Shift+A',
  autoUpdateServices: true,
  lastUpdate: new Date().toISOString(),
  openTabs: [],
  activeTabId: null
};

// Top-level keys of the contextBridge object, so the stub covers the real API
// surface instead of a hand-maintained list that drifts.
function apiKeys() {
  try {
    const preload = fs.readFileSync(path.join(ROOT, 'preload.js'), 'utf8');
    return [...preload.matchAll(/^ {2}([a-zA-Z]+):/gm)].map((m) => m[1]);
  } catch (error) {
    return [];
  }
}

function stubSource() {
  const data = {
    keys: apiKeys(),
    services,
    logins: loginStates,
    enabled,
    config,
    version: pkg.version
  };

  return `/* Generated by scripts/preview-shell.js — stub main process, preview only. */
(function () {
  var data = ${JSON.stringify(data)};
  var noop = function () {};
  var api = {};
  data.keys.forEach(function (key) {
    api[key] = key.indexOf('on') === 0 && /^on[A-Z]/.test(key) ? noop : function () { return Promise.resolve({}); };
  });

  var light = new URLSearchParams(location.search).has('light');

  api.getConfig = function () { return Promise.resolve(Object.assign({}, data.config, { darkMode: !light })); };
  api.saveConfig = function (patch) { Object.assign(data.config, patch || {}); return Promise.resolve(data.config); };
  api.getServices = function () { return Promise.resolve({ ai_services: data.services }); };
  api.getLoginStates = function () { return Promise.resolve(data.logins); };
  api.getTabStates = function () { return Promise.resolve({ tabs: [], activeTabId: null, limit: 3, hardMax: 20 }); };
  api.getLimits = function () { return Promise.resolve({ openTabs: data.enabled.length, limit: 3, minTabs: 1, hardMax: 20 }); };
  api.getSessionStats = function () {
    return Promise.resolve({
      total: 34,
      services: {
        ${enabled.slice(0, 3).map((id, i) => `${JSON.stringify(id)}: { cookies: ${12 - i * 4}, authCookies: ${3 - i}, pinned: ${2 - i}, isolated: ${i === 1}, cacheSize: ${i === 0 ? 2411724 : 0} }`).join(',\n        ')}
      }
    });
  };
  api.getApiStatus = function () {
    return Promise.resolve({ running: true, port: 8788, exposeAll: true, key: 'sk-aihub-preview', services: data.enabled, startedAt: Date.now() - 600000 });
  };
  api.getBlockingStats = function () { return Promise.resolve({ blocked: 148, allowed: 2317 }); };
  api.getAppInfo = function () {
    return Promise.resolve({
      version: data.version, electron: 'preview', chrome: 'preview', node: 'preview',
      platform: navigator.platform || 'preview', arch: 'preview',
      shortcut: data.config.globalShortcut, logPath: '(preview — no log file)'
    });
  };
  api.getUpdateStatus = function () { return Promise.resolve({ status: 'idle', currentVersion: data.version, latestVersion: data.version }); };
  api.getFavicon = function () { return Promise.resolve({ dataUrl: null }); };
  api.openExternal = noop;
  api.setViewBounds = noop;

  window.electronAPI = api;

  // A stand-in for the native view so the surrounding layout is honest: this
  // rectangle is where the WebContentsView paints in the real app.
  function drawSurface() {
    var anchor = document.getElementById('webviews-container');
    if (!anchor || anchor.dataset.previewSurface === '1') return;
    anchor.dataset.previewSurface = '1';
    var surface = document.createElement('div');
    surface.style.cssText = 'position:absolute;inset:0;display:flex;align-items:center;justify-content:center;' +
      'background:linear-gradient(158deg,#0e1015,#141822 60%,#101319);color:#59617a;' +
      "font:600 13px -apple-system,BlinkMacSystemFont,'SF Pro Text',system-ui";
    surface.textContent = 'Chat surface — the native WebContentsView paints here';
    anchor.appendChild(surface);
  }

  window.addEventListener('DOMContentLoaded', function () {
    var params = new URLSearchParams(location.search);
    if (params.has('sidebar') && window.AiHub && window.AiHub.openSidebar) window.AiHub.openSidebar();
    if (params.has('settings') && window.AiHub && window.AiHub.openSettings) {
      window.AiHub.openSettings(params.get('settings') || 'general');
    }
    if (params.has('surface')) drawSurface();
  });

  if (window.localStorage && new URLSearchParams(location.search).has('reset')) {
    window.localStorage.clear();
  }
})();
`;
}

function indexWithStub() {
  const html = fs.readFileSync(path.join(UI_DIR, 'index.html'), 'utf8');
  const tag = '<script src="/__preview-stub.js"></script>\n  ';
  // The stub must land before the first shell script, whatever order index.html
  // uses, and it must be a same-origin file: the page CSP stays in force.
  const firstScript = html.search(/<script\s+src=/);
  if (firstScript === -1) return html.replace('</body>', `${tag}</body>`);
  return html.slice(0, firstScript) + tag + html.slice(firstScript);
}

function send(res, status, body, type = 'text/plain; charset=utf-8') {
  res.writeHead(status, { 'Content-Type': type, 'Cache-Control': 'no-store' });
  res.end(body);
}

const server = http.createServer((req, res) => {
  const urlPath = decodeURIComponent((req.url || '/').split('?')[0]);

  if (urlPath === '/' || urlPath === '/index.html') {
    return send(res, 200, indexWithStub(), 'text/html; charset=utf-8');
  }
  if (urlPath === '/__preview-stub.js') {
    return send(res, 200, stubSource(), 'text/javascript; charset=utf-8');
  }

  const file = path.normalize(path.join(UI_DIR, urlPath));
  if (!file.startsWith(UI_DIR)) return send(res, 403, 'Forbidden');

  fs.readFile(file, (error, buffer) => {
    if (error) return send(res, 404, 'Not found');
    send(res, 200, buffer, MIME[path.extname(file).toLowerCase()] || 'application/octet-stream');
  });
});

server.listen(PORT, HOST, () => {
  console.log(`[preview] renderer shell on http://${HOST === '0.0.0.0' ? '127.0.0.1' : HOST}:${PORT}`);
  console.log('[preview] ?light for the light theme, ?surface to stand in for the native view');
  console.log(`[preview] ${services.length} services, ${enabled.length} enabled, logins stubbed`);
});
